package com.radcom.weather.data.objects

import com.github.kittinunf.fuel.core.ResponseDeserializable
import com.google.gson.Gson

//1.AUTO-GENERATED by https://github.com/wuseal/JsonToKotlinClass
//2.Simplified
data class OpenWeatherModel(
//    val calctime: Double,
//    val cnt: Int,
//    val cod: String,
    val list: List<City>
)

data class City(
//    val clouds: Clouds,
    val coord: Coord,
//    val dt: Int,
//    val id: Int,
    val main: Main,
    val name: String,
//    val rain: Rain,
//    val weather: List<Weather>,
    val wind: Wind
)

//data class Clouds(
//    val all: Int
//)

data class Coord(
    val lat: Double,
    val lon: Double
)

data class Main(
//    val grnd_level: Double,
//    val humidity: Int,
//    val pressure: Double,
//    val sea_level: Double,
    val temp: Double,
    val temp_max: Double,
    val temp_min: Double
)

//data class Rain(
//    val `3h`: Double
//)

//data class Weather(
//    val description: String,
//    val icon: String,
//    val id: Int,
//    val main: String
//)

data class Wind(
//    val deg: Double,
    val speed: Double,
//    val var_beg: Int,
//    val var_end: Int
)

// Needed for awaitObjectResponse, awaitObject, etc.
class OpenWeatherDeserializer : ResponseDeserializable<OpenWeatherModel> {
    override fun deserialize(content: String): OpenWeatherModel? =
        Gson().fromJson(content, OpenWeatherModel::class.java)
}
